-- MySQL-compatible insert data generated from live local MySQL database
-- Database: indcool
-- Date: 2026-08-21
-- Rule: full data for item_masters; sample up to 5 row(s) for other tables

SET FOREIGN_KEY_CHECKS=0;
START TRANSACTION;

-- Table: alembic_version
-- Export mode: sample data (1 of 1 row(s))
DELETE FROM `alembic_version`;
INSERT INTO `alembic_version` (`version_num`) VALUES ('0019_link_service_requests_to_complaints');

-- Table: calls
-- Export mode: sample data (0 of 0 row(s))
-- No live sample data in `calls`

-- Table: claim_photos
-- Export mode: sample data (0 of 0 row(s))
-- No live sample data in `claim_photos`

-- Table: claims
-- Export mode: sample data (0 of 0 row(s))
-- No live sample data in `claims`

-- Table: complaint_status_logs
-- Export mode: sample data (5 of 22 row(s))
DELETE FROM `complaint_status_logs`;
INSERT INTO `complaint_status_logs` (`id`, `complaint_id`, `old_status`, `new_status`, `changed_by`, `remark`, `document_path`, `action_taken`, `changed_at`) VALUES (1, 1, NULL, 'Pending', 1, 'Seeded sample Service complaint', NULL, NULL, '2026-07-29 08:53:39');
INSERT INTO `complaint_status_logs` (`id`, `complaint_id`, `old_status`, `new_status`, `changed_by`, `remark`, `document_path`, `action_taken`, `changed_at`) VALUES (2, 2, NULL, 'In Process', 1, 'Seeded sample Installation complaint', NULL, NULL, '2026-07-29 08:53:39');
INSERT INTO `complaint_status_logs` (`id`, `complaint_id`, `old_status`, `new_status`, `changed_by`, `remark`, `document_path`, `action_taken`, `changed_at`) VALUES (3, 3, NULL, 'Pending', 1, 'Seeded sample Sales complaint', NULL, NULL, '2026-07-29 08:53:39');
INSERT INTO `complaint_status_logs` (`id`, `complaint_id`, `old_status`, `new_status`, `changed_by`, `remark`, `document_path`, `action_taken`, `changed_at`) VALUES (4, 4, NULL, 'Pending', 1, 'Seeded additional service complaint', NULL, NULL, '2026-07-29 08:53:39');
INSERT INTO `complaint_status_logs` (`id`, `complaint_id`, `old_status`, `new_status`, `changed_by`, `remark`, `document_path`, `action_taken`, `changed_at`) VALUES (5, 5, NULL, 'In Process', 1, 'Seeded additional service complaint', NULL, NULL, '2026-07-29 08:53:39');

-- Table: couriers
-- Export mode: sample data (4 of 4 row(s))
DELETE FROM `couriers`;
INSERT INTO `couriers` (`id`, `courier_name`, `contact_name`, `contact_mobile`, `email`, `address`, `created_at`, `updated_at`, `deleted_at`) VALUES (1, 'API-QA-0c623bcd Courier', 'QA Courier Updated', '9990002222', 'qa.courier@example.com', 'QA courier address', '2026-07-31 16:55:53', '2026-07-31 22:25:53', '2026-07-31 16:55:53');
INSERT INTO `couriers` (`id`, `courier_name`, `contact_name`, `contact_mobile`, `email`, `address`, `created_at`, `updated_at`, `deleted_at`) VALUES (2, 'API-QA-f69170de Courier', 'QA Courier Updated', '9990002222', 'qa.courier@example.com', 'QA courier address', '2026-07-31 16:57:38', '2026-07-31 22:27:39', '2026-07-31 16:57:39');
INSERT INTO `couriers` (`id`, `courier_name`, `contact_name`, `contact_mobile`, `email`, `address`, `created_at`, `updated_at`, `deleted_at`) VALUES (3, 'API-QA-a1016610 Courier', 'QA Courier Updated', '9990002222', 'qa.courier@example.com', 'QA courier address', '2026-07-31 17:00:11', '2026-07-31 22:30:12', '2026-07-31 17:00:12');
INSERT INTO `couriers` (`id`, `courier_name`, `contact_name`, `contact_mobile`, `email`, `address`, `created_at`, `updated_at`, `deleted_at`) VALUES (4, 'Delivery', 'Ramesh kumar', '7045678934', 'dubeyrajee@gmail.com', 'Supriya  Road', '2026-08-04 13:26:04', '2026-08-04 13:26:04', NULL);

-- Table: item_masters
-- Export mode: full data (19 row(s))
DELETE FROM `item_masters`;
INSERT INTO `item_masters` (`id`, `item_code`, `item_name`, `category`, `description`, `brand`, `unit`, `hsn_code`, `mrp`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (1, '8908012210436', 'SPLIT AC IDCACS18K5', 'AC', NULL, NULL, NULL, NULL, NULL, 1, '2026-07-29 05:14:42', '2026-07-29 05:14:42', NULL);
INSERT INTO `item_masters` (`id`, `item_code`, `item_name`, `category`, `description`, `brand`, `unit`, `hsn_code`, `mrp`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (2, '8908012210443', 'WINDOW AC IDCACW15K3', 'AC', NULL, NULL, NULL, NULL, NULL, 1, '2026-07-29 05:14:42', '2026-07-29 05:14:42', NULL);
INSERT INTO `item_masters` (`id`, `item_code`, `item_name`, `category`, `description`, `brand`, `unit`, `hsn_code`, `mrp`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (3, '8908012210450', 'GEYSER IDCGYS25L', 'Geyser', NULL, NULL, NULL, NULL, NULL, 1, '2026-07-29 05:14:42', '2026-07-29 05:14:42', NULL);
INSERT INTO `item_masters` (`id`, `item_code`, `item_name`, `category`, `description`, `brand`, `unit`, `hsn_code`, `mrp`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (4, '8908012210467', 'FRIDGE IDCFRD250L', 'Fridge', NULL, NULL, NULL, NULL, NULL, 1, '2026-07-29 08:53:36', '2026-07-29 08:53:36', NULL);
INSERT INTO `item_masters` (`id`, `item_code`, `item_name`, `category`, `description`, `brand`, `unit`, `hsn_code`, `mrp`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (5, '8908012210474', 'AIR COOLER IDCCLR40L', 'Cooler', NULL, NULL, NULL, NULL, NULL, 1, '2026-07-29 08:53:36', '2026-07-29 08:53:36', NULL);
INSERT INTO `item_masters` (`id`, `item_code`, `item_name`, `category`, `description`, `brand`, `unit`, `hsn_code`, `mrp`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (6, '8908012210481', 'SPLIT AC IDCACS24K5', 'AC', NULL, NULL, NULL, NULL, NULL, 1, '2026-07-29 08:53:36', '2026-07-29 08:53:36', NULL);
INSERT INTO `item_masters` (`id`, `item_code`, `item_name`, `category`, `description`, `brand`, `unit`, `hsn_code`, `mrp`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (7, '8908012210498', 'WINDOW AC IDCACW18K3', 'AC', NULL, NULL, NULL, NULL, NULL, 1, '2026-07-29 08:53:36', '2026-07-29 08:53:36', NULL);
INSERT INTO `item_masters` (`id`, `item_code`, `item_name`, `category`, `description`, `brand`, `unit`, `hsn_code`, `mrp`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (8, '8908012210504', 'GEYSER IDCGYS15L', 'Geyser', NULL, NULL, NULL, NULL, NULL, 1, '2026-07-29 08:53:36', '2026-07-29 08:53:36', NULL);
INSERT INTO `item_masters` (`id`, `item_code`, `item_name`, `category`, `description`, `brand`, `unit`, `hsn_code`, `mrp`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (9, '8908012210511', 'FRIDGE IDCFRD320L', 'Fridge', NULL, NULL, NULL, NULL, NULL, 1, '2026-07-29 08:53:36', '2026-07-29 08:53:36', NULL);
INSERT INTO `item_masters` (`id`, `item_code`, `item_name`, `category`, `description`, `brand`, `unit`, `hsn_code`, `mrp`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (10, '8908012210528', 'AIR COOLER IDCCLR60L', 'Cooler', NULL, NULL, NULL, NULL, NULL, 1, '2026-07-29 08:53:36', '2026-07-29 08:53:36', NULL);
INSERT INTO `item_masters` (`id`, `item_code`, `item_name`, `category`, `description`, `brand`, `unit`, `hsn_code`, `mrp`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (11, '8908012210535', 'SPLIT AC IDCACS13K3E', 'AC', NULL, NULL, NULL, NULL, NULL, 1, '2026-07-29 08:53:36', '2026-07-29 08:53:36', NULL);
INSERT INTO `item_masters` (`id`, `item_code`, `item_name`, `category`, `description`, `brand`, `unit`, `hsn_code`, `mrp`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (12, '8908012210542', 'WINDOW AC IDCACW24K3E', 'AC', NULL, NULL, NULL, NULL, NULL, 1, '2026-07-29 08:53:36', '2026-07-29 08:53:36', NULL);
INSERT INTO `item_masters` (`id`, `item_code`, `item_name`, `category`, `description`, `brand`, `unit`, `hsn_code`, `mrp`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (13, '8908012210559', 'GEYSER IDCWH35L', 'Geyser', NULL, NULL, NULL, NULL, NULL, 1, '2026-07-29 08:53:36', '2026-07-29 08:53:36', NULL);
INSERT INTO `item_masters` (`id`, `item_code`, `item_name`, `category`, `description`, `brand`, `unit`, `hsn_code`, `mrp`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (14, '8908012210566', 'FRIDGE IDCFRD360L', 'Fridge', NULL, NULL, NULL, NULL, NULL, 1, '2026-07-29 08:53:36', '2026-07-29 08:53:36', NULL);
INSERT INTO `item_masters` (`id`, `item_code`, `item_name`, `category`, `description`, `brand`, `unit`, `hsn_code`, `mrp`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (15, '8908012210573', 'AIR COOLER IDCCLR80L', 'Cooler', NULL, NULL, NULL, NULL, NULL, 1, '2026-07-29 08:53:36', '2026-07-29 08:53:36', NULL);
INSERT INTO `item_masters` (`id`, `item_code`, `item_name`, `category`, `description`, `brand`, `unit`, `hsn_code`, `mrp`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (16, 'API-QA-0c623bcd-ITEM', 'API-QA-0c623bcd Item', 'AC', NULL, 'QA-UPDATED', 'pcs', NULL, 999.00, 1, '2026-07-31 16:55:52', '2026-07-31 22:25:53', '2026-07-31 16:55:53');
INSERT INTO `item_masters` (`id`, `item_code`, `item_name`, `category`, `description`, `brand`, `unit`, `hsn_code`, `mrp`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (17, 'API-QA-f69170de-ITEM', 'API-QA-f69170de Item', 'AC', NULL, 'QA-UPDATED', 'pcs', NULL, 999.00, 1, '2026-07-31 16:57:37', '2026-07-31 22:27:38', '2026-07-31 16:57:38');
INSERT INTO `item_masters` (`id`, `item_code`, `item_name`, `category`, `description`, `brand`, `unit`, `hsn_code`, `mrp`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (18, 'API-QA-a1016610-ITEM', 'API-QA-a1016610 Item', 'AC', NULL, 'QA-UPDATED', 'pcs', NULL, 999.00, 1, '2026-07-31 17:00:11', '2026-07-31 22:30:11', '2026-07-31 17:00:11');
INSERT INTO `item_masters` (`id`, `item_code`, `item_name`, `category`, `description`, `brand`, `unit`, `hsn_code`, `mrp`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (19, '12345678', 'dhananjai ac', 'Split AC', 'ASDDF', 'indcool', 'Pcs', '8415', 45000.00, 1, '2026-08-01 03:45:53', '2026-08-01 03:45:53', NULL);

-- Table: market_categories
-- Export mode: sample data (0 of 0 row(s))
-- No live sample data in `market_categories`

-- Table: market_items
-- Export mode: sample data (0 of 0 row(s))
-- No live sample data in `market_items`

-- Table: market_order_items
-- Export mode: sample data (3 of 3 row(s))
DELETE FROM `market_order_items`;
INSERT INTO `market_order_items` (`id`, `order_id`, `item_id`, `qty`, `unit_price`, `subtotal`, `created_at`, `updated_at`) VALUES (1, 1, 1, 2, 2500.00, 5000.00, '2026-07-31 16:56:02', '2026-07-31 16:56:02');
INSERT INTO `market_order_items` (`id`, `order_id`, `item_id`, `qty`, `unit_price`, `subtotal`, `created_at`, `updated_at`) VALUES (2, 2, 2, 2, 2500.00, 5000.00, '2026-07-31 16:57:53', '2026-07-31 16:57:53');
INSERT INTO `market_order_items` (`id`, `order_id`, `item_id`, `qty`, `unit_price`, `subtotal`, `created_at`, `updated_at`) VALUES (3, 3, 3, 2, 2500.00, 5000.00, '2026-07-31 17:00:19', '2026-07-31 17:00:19');

-- Table: market_orders
-- Export mode: sample data (0 of 0 row(s))
-- No live sample data in `market_orders`

-- Table: market_users
-- Export mode: sample data (0 of 0 row(s))
-- No live sample data in `market_users`

-- Table: order_items
-- Export mode: sample data (5 of 88 row(s))
DELETE FROM `order_items`;
INSERT INTO `order_items` (`id`, `order_id`, `item_id`, `serial_no`, `serial_no_2`, `item_qty`, `pcb_warranty_years`, `component_warranty_years`, `machine_warranty_years`, `free_service_count`, `service_consume_count`, `installation_status`, `created_at`, `updated_at`, `item_code`, `dry_free_service_count`, `wet_free_service_count`) VALUES (1, 1, 1, 'SN00101', 'SN2-1-001', 1, 1, 2, 3, 4, 0, 'Not Requested', '2026-07-29 08:53:39', '2026-08-21 07:35:59', '8908012210436', 2, 2);
INSERT INTO `order_items` (`id`, `order_id`, `item_id`, `serial_no`, `serial_no_2`, `item_qty`, `pcb_warranty_years`, `component_warranty_years`, `machine_warranty_years`, `free_service_count`, `service_consume_count`, `installation_status`, `created_at`, `updated_at`, `item_code`, `dry_free_service_count`, `wet_free_service_count`) VALUES (2, 1, 1, 'SN00102', 'SN2-1-002', 1, 1, 2, 3, 4, 0, 'Not Requested', '2026-07-29 08:53:39', '2026-08-21 07:35:59', '8908012210436', 2, 2);
INSERT INTO `order_items` (`id`, `order_id`, `item_id`, `serial_no`, `serial_no_2`, `item_qty`, `pcb_warranty_years`, `component_warranty_years`, `machine_warranty_years`, `free_service_count`, `service_consume_count`, `installation_status`, `created_at`, `updated_at`, `item_code`, `dry_free_service_count`, `wet_free_service_count`) VALUES (3, 1, 1, 'SN00103', 'SN2-1-003', 1, 1, 2, 3, 4, 0, 'Not Requested', '2026-07-29 08:53:39', '2026-08-21 07:35:59', '8908012210436', 2, 2);
INSERT INTO `order_items` (`id`, `order_id`, `item_id`, `serial_no`, `serial_no_2`, `item_qty`, `pcb_warranty_years`, `component_warranty_years`, `machine_warranty_years`, `free_service_count`, `service_consume_count`, `installation_status`, `created_at`, `updated_at`, `item_code`, `dry_free_service_count`, `wet_free_service_count`) VALUES (4, 2, 1, 'SN00201', 'SN2-2-001', 1, 1, 2, 3, 4, 0, 'Not Requested', '2026-07-29 08:53:39', '2026-08-21 07:35:59', '8908012210436', 2, 2);
INSERT INTO `order_items` (`id`, `order_id`, `item_id`, `serial_no`, `serial_no_2`, `item_qty`, `pcb_warranty_years`, `component_warranty_years`, `machine_warranty_years`, `free_service_count`, `service_consume_count`, `installation_status`, `created_at`, `updated_at`, `item_code`, `dry_free_service_count`, `wet_free_service_count`) VALUES (5, 2, 1, 'SN00202', 'SN2-2-002', 1, 1, 2, 3, 4, 0, 'Not Requested', '2026-07-29 08:53:39', '2026-08-21 07:35:59', '8908012210436', 2, 2);

-- Table: orders
-- Export mode: sample data (5 of 45 row(s))
DELETE FROM `orders`;
INSERT INTO `orders` (`id`, `order_no`, `order_date`, `oem_bill_no`, `vendor_id`, `customer_name`, `customer_contact`, `customer_email`, `customer_city`, `customer_state`, `customer_address`, `courier_id`, `lrn_no`, `vendor_bill_no`, `vendor_bill_date`, `status`, `expected_delivery_date`, `actual_delivery_date`, `order_file_path`, `created_by`, `created_at`, `updated_at`, `deleted_at`) VALUES (1, 'VEND-ORD-201', '2024-07-15', NULL, 1, 'Cust 1', '9876543210', NULL, 'Delhi', NULL, NULL, NULL, NULL, NULL, NULL, 'Delivered', NULL, NULL, NULL, 1, '2026-07-29 08:53:39', '2026-07-29 08:53:39', NULL);
INSERT INTO `orders` (`id`, `order_no`, `order_date`, `oem_bill_no`, `vendor_id`, `customer_name`, `customer_contact`, `customer_email`, `customer_city`, `customer_state`, `customer_address`, `courier_id`, `lrn_no`, `vendor_bill_no`, `vendor_bill_date`, `status`, `expected_delivery_date`, `actual_delivery_date`, `order_file_path`, `created_by`, `created_at`, `updated_at`, `deleted_at`) VALUES (2, 'VEND-ORD-202', '2024-07-20', NULL, 1, 'Cust 2', '9876543211', NULL, 'Mumbai', NULL, NULL, NULL, NULL, NULL, NULL, 'Delivered', NULL, NULL, NULL, 1, '2026-07-29 08:53:39', '2026-07-29 08:53:39', NULL);
INSERT INTO `orders` (`id`, `order_no`, `order_date`, `oem_bill_no`, `vendor_id`, `customer_name`, `customer_contact`, `customer_email`, `customer_city`, `customer_state`, `customer_address`, `courier_id`, `lrn_no`, `vendor_bill_no`, `vendor_bill_date`, `status`, `expected_delivery_date`, `actual_delivery_date`, `order_file_path`, `created_by`, `created_at`, `updated_at`, `deleted_at`) VALUES (3, 'VEND-ORD-203', '2024-07-10', NULL, 1, 'Cust S', '9990000005', NULL, 'TestCity', NULL, NULL, NULL, NULL, NULL, NULL, 'Pending', NULL, NULL, NULL, 1, '2026-07-29 08:53:39', '2026-07-29 08:53:39', NULL);
INSERT INTO `orders` (`id`, `order_no`, `order_date`, `oem_bill_no`, `vendor_id`, `customer_name`, `customer_contact`, `customer_email`, `customer_city`, `customer_state`, `customer_address`, `courier_id`, `lrn_no`, `vendor_bill_no`, `vendor_bill_date`, `status`, `expected_delivery_date`, `actual_delivery_date`, `order_file_path`, `created_by`, `created_at`, `updated_at`, `deleted_at`) VALUES (4, 'VEND-ORD-204', '2024-06-15', NULL, 1, 'Cust 3', '9876543212', NULL, 'Bangalore', NULL, NULL, NULL, NULL, NULL, NULL, 'In Transit', NULL, NULL, NULL, 1, '2026-07-29 08:53:39', '2026-07-29 08:53:39', NULL);
INSERT INTO `orders` (`id`, `order_no`, `order_date`, `oem_bill_no`, `vendor_id`, `customer_name`, `customer_contact`, `customer_email`, `customer_city`, `customer_state`, `customer_address`, `courier_id`, `lrn_no`, `vendor_bill_no`, `vendor_bill_date`, `status`, `expected_delivery_date`, `actual_delivery_date`, `order_file_path`, `created_by`, `created_at`, `updated_at`, `deleted_at`) VALUES (5, 'VEND-ORD-205', '2024-07-25', NULL, 1, 'Cust 4', '9876543213', NULL, 'Pune', NULL, NULL, NULL, NULL, NULL, NULL, 'Delivered', NULL, NULL, NULL, 1, '2026-07-29 08:53:40', '2026-07-29 08:53:40', NULL);

-- Table: permissions
-- Export mode: sample data (5 of 100 row(s))
DELETE FROM `permissions`;
INSERT INTO `permissions` (`id`, `role_id`, `module`, `sub_module`, `can_view`, `can_create`, `can_edit`, `can_delete`, `can_export`) VALUES (1, 1, 'complaints', NULL, 1, 1, 1, 1, 1);
INSERT INTO `permissions` (`id`, `role_id`, `module`, `sub_module`, `can_view`, `can_create`, `can_edit`, `can_delete`, `can_export`) VALUES (2, 1, 'installations', NULL, 1, 1, 1, 1, 1);
INSERT INTO `permissions` (`id`, `role_id`, `module`, `sub_module`, `can_view`, `can_create`, `can_edit`, `can_delete`, `can_export`) VALUES (3, 1, 'orders', NULL, 1, 1, 1, 1, 1);
INSERT INTO `permissions` (`id`, `role_id`, `module`, `sub_module`, `can_view`, `can_create`, `can_edit`, `can_delete`, `can_export`) VALUES (4, 1, 'vendors', NULL, 1, 1, 1, 1, 1);
INSERT INTO `permissions` (`id`, `role_id`, `module`, `sub_module`, `can_view`, `can_create`, `can_edit`, `can_delete`, `can_export`) VALUES (5, 1, 'items', NULL, 1, 1, 1, 1, 1);

-- Table: projects
-- Export mode: sample data (0 of 0 row(s))
-- No live sample data in `projects`

-- Table: roles
-- Export mode: sample data (5 of 8 row(s))
DELETE FROM `roles`;
INSERT INTO `roles` (`id`, `name`, `description`, `created_at`, `updated_at`) VALUES (1, 'admin', 'Administrator — full access to all modules', '2026-07-29 05:14:42', '2026-08-02 17:13:21');
INSERT INTO `roles` (`id`, `name`, `description`, `created_at`, `updated_at`) VALUES (2, 'callcenter', 'Call Center — create/view complaints, log calls', '2026-07-29 05:14:42', '2026-08-02 17:13:21');
INSERT INTO `roles` (`id`, `name`, `description`, `created_at`, `updated_at`) VALUES (3, 'engineer', 'Engineer — view assigned complaints/installations, update status & work reports', '2026-07-29 05:14:42', '2026-08-02 17:13:21');
INSERT INTO `roles` (`id`, `name`, `description`, `created_at`, `updated_at`) VALUES (4, 'vendor', 'Vendor — read-only access to own orders', '2026-07-29 05:14:42', '2026-08-02 17:13:21');
INSERT INTO `roles` (`id`, `name`, `description`, `created_at`, `updated_at`) VALUES (5, 'public', 'Public User — submit complaint via public form (no login UI)', '2026-07-29 05:14:42', '2026-08-02 17:13:21');

-- Table: service_document_rules
-- Export mode: sample data (0 of 0 row(s))
-- No live sample data in `service_document_rules`

-- Table: users
-- Export mode: sample data (5 of 11 row(s))
DELETE FROM `users`;
INSERT INTO `users` (`id`, `name`, `email`, `password_hash`, `role`, `phone`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (1, 'Administrator', 'admin@indcool.com', '$2b$12$CNn9///7TTLe1lBtDRQiS.lrIxghGP7/Src8f/yjAW8myRs16GTwC', 'admin', '9999999999', 1, '2026-07-29 05:14:42', '2026-07-29 14:35:26', NULL);
INSERT INTO `users` (`id`, `name`, `email`, `password_hash`, `role`, `phone`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (2, 'Ravi Kumar', 'ravi@indcool.com', '$2b$12$iVTzAgc5zuMdr4XP4XPwe.5jOFdFEOGY1sKvkWiMvXG3u29D3myg2', 'engineer', '9810000001', 1, '2026-07-29 08:53:37', '2026-07-29 08:53:37', NULL);
INSERT INTO `users` (`id`, `name`, `email`, `password_hash`, `role`, `phone`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (3, 'Sunita Patel', 'sunita@indcool.com', '$2b$12$SJq3Rqz3x58quKgc2t.KQeL4Mx3qQc2/4Gb.jtLM2gCDX3UK9aGei', 'engineer', '9810000002', 1, '2026-07-29 08:53:37', '2026-08-21 11:02:35', NULL);
INSERT INTO `users` (`id`, `name`, `email`, `password_hash`, `role`, `phone`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (4, 'Arjun Sharma', 'arjun@indcool.com', '$2b$12$WKl5tqqopvldnELagm7ejeq73TPgWShAMAuNEqAYv6KgjhIfuuCaa', 'engineer', '9810000003', 1, '2026-07-29 08:53:37', '2026-07-29 08:53:37', NULL);
INSERT INTO `users` (`id`, `name`, `email`, `password_hash`, `role`, `phone`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (5, 'Priya Mehta', 'sales@indcool.com', '$2b$12$pTA03PuMbxinLtGvoMtyIeTX57Qzs26thEZlVATL58FnGA6miNBvu', 'sales', '9810010101', 1, '2026-07-29 08:53:38', '2026-07-29 08:53:38', NULL);

-- Table: vendors
-- Export mode: sample data (2 of 2 row(s))
DELETE FROM `vendors`;
INSERT INTO `vendors` (`id`, `vendor_code`, `name_of_firm`, `contact_name`, `contact_mobile`, `email`, `gst_no`, `address`, `state`, `district`, `pincode`, `latitude`, `longitude`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (1, 'VEND-001', 'Vendor Test Co', 'Vendor User', '9876543200', 'vendor@indcool.com', '27AAPPU1234A1Z0', 'New Delhi', 'Delhi', 'Central Delhi', '110001', NULL, NULL, 1, '2026-07-29 08:53:39', '2026-07-29 08:53:39', NULL);
INSERT INTO `vendors` (`id`, `vendor_code`, `name_of_firm`, `contact_name`, `contact_mobile`, `email`, `gst_no`, `address`, `state`, `district`, `pincode`, `latitude`, `longitude`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES (2, 'VEND-002', 'Vendor One Pvt Ltd', 'Vendor One', '9876543201', 'vendor1@indcool.com', '27AAECA1234A1Z5', 'Gurugram, Haryana', 'Haryana', 'Gurugram', '122001', NULL, NULL, 1, '2026-07-30 03:54:46', '2026-07-30 03:54:46', NULL);

-- Table: workflow_tasks
-- Export mode: sample data (0 of 0 row(s))
-- No live sample data in `workflow_tasks`

-- Table: complaints
-- Export mode: sample data (5 of 14 row(s))
DELETE FROM `complaints`;
INSERT INTO `complaints` (`id`, `comp_no`, `comp_date`, `customer_name`, `customer_mobile`, `customer_email`, `customer_address`, `model_details`, `problem_description`, `query_type`, `status`, `status_date`, `assigned_engineer`, `remark`, `service_proof_path`, `access_code`, `send_sms`, `created_by`, `source`, `created_at`, `updated_at`, `deleted_at`, `order_item_id`, `serial_no`) VALUES (1, 'IDC_SEED_1785315219105', '2026-07-28', 'Demo Service Customer', '9990000001', 'demo-service@example.com', 'Sector 21, Noida, UP', 'SPLIT AC IDCACS18K5', 'AC compressor making rattling noise; intermittent cooling.', 'Service', 'Pending', NULL, NULL, NULL, NULL, '247088', 1, 1, 'callcenter', '2026-07-29 08:53:39', '2026-07-29 08:53:39', NULL, NULL, NULL);
INSERT INTO `complaints` (`id`, `comp_no`, `comp_date`, `customer_name`, `customer_mobile`, `customer_email`, `customer_address`, `model_details`, `problem_description`, `query_type`, `status`, `status_date`, `assigned_engineer`, `remark`, `service_proof_path`, `access_code`, `send_sms`, `created_by`, `source`, `created_at`, `updated_at`, `deleted_at`, `order_item_id`, `serial_no`) VALUES (2, 'IDC_SEED_1785315219106', '2026-07-28', 'Demo Installation Customer', '9990000002', 'demo-install@example.com', 'Sector 18, Gurugram, HR', 'WINDOW AC IDCACW18K3', 'Customer wants installation coordination for new AC unit.', 'Installation', 'In Process', NULL, NULL, NULL, NULL, '336705', 1, 1, 'callcenter', '2026-07-29 08:53:39', '2026-07-29 08:53:39', NULL, NULL, NULL);
INSERT INTO `complaints` (`id`, `comp_no`, `comp_date`, `customer_name`, `customer_mobile`, `customer_email`, `customer_address`, `model_details`, `problem_description`, `query_type`, `status`, `status_date`, `assigned_engineer`, `remark`, `service_proof_path`, `access_code`, `send_sms`, `created_by`, `source`, `created_at`, `updated_at`, `deleted_at`, `order_item_id`, `serial_no`) VALUES (3, 'IDC_SEED_1785315219107', '2026-07-28', 'Demo Sales Prospect', '9990000003', 'demo-sales@example.com', 'Plot 9, Pune, MH', 'GEYSER IDCGYS15L', 'Interested in bulk purchase for commercial premises.', 'Sales', 'Pending', NULL, NULL, NULL, NULL, '364448', 1, 1, 'callcenter', '2026-07-29 08:53:39', '2026-07-29 08:53:39', NULL, NULL, NULL);
INSERT INTO `complaints` (`id`, `comp_no`, `comp_date`, `customer_name`, `customer_mobile`, `customer_email`, `customer_address`, `model_details`, `problem_description`, `query_type`, `status`, `status_date`, `assigned_engineer`, `remark`, `service_proof_path`, `access_code`, `send_sms`, `created_by`, `source`, `created_at`, `updated_at`, `deleted_at`, `order_item_id`, `serial_no`) VALUES (4, 'IDC_SEED_1785315219108', '2026-07-28', 'Nitin Bansal', '9990000004', 'nitin.bansal@example.com', 'Sector 62, Noida, UP', 'SPLIT AC IDCACS24K5', 'Customer reports unusual noise after startup.', 'Service', 'Pending', NULL, NULL, NULL, NULL, '770237', 1, 1, 'callcenter', '2026-07-29 08:53:39', '2026-07-29 08:53:39', NULL, NULL, NULL);
INSERT INTO `complaints` (`id`, `comp_no`, `comp_date`, `customer_name`, `customer_mobile`, `customer_email`, `customer_address`, `model_details`, `problem_description`, `query_type`, `status`, `status_date`, `assigned_engineer`, `remark`, `service_proof_path`, `access_code`, `send_sms`, `created_by`, `source`, `created_at`, `updated_at`, `deleted_at`, `order_item_id`, `serial_no`) VALUES (5, 'IDC_SEED_1785315219109', '2026-07-28', 'Anjali Rao', '9990000005', 'anjali.rao@example.com', 'Whitefield, Bengaluru, KA', 'FRIDGE IDCFRD360L', 'Customer wants a service visit for cooling issue.', 'Service', 'In Process', NULL, NULL, NULL, NULL, '018916', 1, 1, 'callcenter', '2026-07-29 08:53:39', '2026-07-29 08:53:39', NULL, NULL, NULL);

-- Table: payment_transactions
-- Export mode: sample data (5 of 6 row(s))
DELETE FROM `payment_transactions`;
INSERT INTO `payment_transactions` (`id`, `payment_type`, `total_amount`, `request_count`, `recorded_by_user_id`, `engineer_user_id`, `recorded_at`) VALUES (1, 'UPI', 4800.00, 2, 1, 2, '2026-08-08 10:54:37');
INSERT INTO `payment_transactions` (`id`, `payment_type`, `total_amount`, `request_count`, `recorded_by_user_id`, `engineer_user_id`, `recorded_at`) VALUES (2, 'UPI', 1000.00, 1, 1, 2, '2026-08-09 19:07:03');
INSERT INTO `payment_transactions` (`id`, `payment_type`, `total_amount`, `request_count`, `recorded_by_user_id`, `engineer_user_id`, `recorded_at`) VALUES (3, 'UPI', 2500.00, 1, 1, 2, '2026-08-20 23:13:18');
INSERT INTO `payment_transactions` (`id`, `payment_type`, `total_amount`, `request_count`, `recorded_by_user_id`, `engineer_user_id`, `recorded_at`) VALUES (4, 'UPI', 2500.00, 1, 1, 2, '2026-08-20 23:20:10');
INSERT INTO `payment_transactions` (`id`, `payment_type`, `total_amount`, `request_count`, `recorded_by_user_id`, `engineer_user_id`, `recorded_at`) VALUES (5, 'UPI', 5000.00, 2, 1, 3, '2026-08-21 11:11:47');

-- Table: serial_history_events
-- Export mode: sample data (5 of 155 row(s))
DELETE FROM `serial_history_events`;
INSERT INTO `serial_history_events` (`id`, `order_item_id`, `serial_no`, `serial_no_2`, `event_type`, `event_subtype`, `event_at`, `performed_by_user_id`, `performed_by_name`, `source_table`, `source_id`, `title`, `description`, `remarks`, `metadata_json`, `created_at`) VALUES (1, 3, 'SN2-1-003', 'SN00103', 'ORDER', 'ORDER_CREATED', '2026-07-29 08:53:39', 1, 'Administrator', 'orders', 1, 'Order created', 'Order VEND-ORD-201 created for Cust 1.', NULL, '{''status'': ''Delivered'', ''order_no'': ''VEND-ORD-201'', ''item_code'': ''8908012210436'', ''item_name'': ''SPLIT AC IDCACS18K5'', ''vendor_name'': ''Vendor Test Co'', ''customer_name'': ''Cust 1'', ''customer_contact'': ''9876543210''}', '2026-08-04 14:30:15');
INSERT INTO `serial_history_events` (`id`, `order_item_id`, `serial_no`, `serial_no_2`, `event_type`, `event_subtype`, `event_at`, `performed_by_user_id`, `performed_by_name`, `source_table`, `source_id`, `title`, `description`, `remarks`, `metadata_json`, `created_at`) VALUES (2, 2, 'SN2-1-002', 'SN00102', 'ORDER', 'ORDER_CREATED', '2026-07-29 08:53:39', 1, 'Administrator', 'orders', 1, 'Order created', 'Order VEND-ORD-201 created for Cust 1.', NULL, '{''status'': ''Delivered'', ''order_no'': ''VEND-ORD-201'', ''item_code'': ''8908012210436'', ''item_name'': ''SPLIT AC IDCACS18K5'', ''vendor_name'': ''Vendor Test Co'', ''customer_name'': ''Cust 1'', ''customer_contact'': ''9876543210''}', '2026-08-04 14:30:15');
INSERT INTO `serial_history_events` (`id`, `order_item_id`, `serial_no`, `serial_no_2`, `event_type`, `event_subtype`, `event_at`, `performed_by_user_id`, `performed_by_name`, `source_table`, `source_id`, `title`, `description`, `remarks`, `metadata_json`, `created_at`) VALUES (3, 1, 'SN2-1-001', 'SN00101', 'ORDER', 'ORDER_CREATED', '2026-07-29 08:53:39', 1, 'Administrator', 'orders', 1, 'Order created', 'Order VEND-ORD-201 created for Cust 1.', NULL, '{''status'': ''Delivered'', ''order_no'': ''VEND-ORD-201'', ''item_code'': ''8908012210436'', ''item_name'': ''SPLIT AC IDCACS18K5'', ''vendor_name'': ''Vendor Test Co'', ''customer_name'': ''Cust 1'', ''customer_contact'': ''9876543210''}', '2026-08-04 14:30:15');
INSERT INTO `serial_history_events` (`id`, `order_item_id`, `serial_no`, `serial_no_2`, `event_type`, `event_subtype`, `event_at`, `performed_by_user_id`, `performed_by_name`, `source_table`, `source_id`, `title`, `description`, `remarks`, `metadata_json`, `created_at`) VALUES (4, 3, 'SN00103', 'SN2-1-003', 'ORDER', 'ORDER_CREATED', '2026-07-29 08:53:39', 1, 'Administrator', 'orders', 1, 'Order created', 'Order VEND-ORD-201 created for Cust 1.', NULL, '{''status'': ''Delivered'', ''order_no'': ''VEND-ORD-201'', ''item_code'': ''8908012210436'', ''item_name'': ''SPLIT AC IDCACS18K5'', ''vendor_name'': ''Vendor Test Co'', ''customer_name'': ''Cust 1'', ''customer_contact'': ''9876543210''}', '2026-08-04 14:30:15');
INSERT INTO `serial_history_events` (`id`, `order_item_id`, `serial_no`, `serial_no_2`, `event_type`, `event_subtype`, `event_at`, `performed_by_user_id`, `performed_by_name`, `source_table`, `source_id`, `title`, `description`, `remarks`, `metadata_json`, `created_at`) VALUES (5, 2, 'SN00102', 'SN2-1-002', 'ORDER', 'ORDER_CREATED', '2026-07-29 08:53:39', 1, 'Administrator', 'orders', 1, 'Order created', 'Order VEND-ORD-201 created for Cust 1.', NULL, '{''status'': ''Delivered'', ''order_no'': ''VEND-ORD-201'', ''item_code'': ''8908012210436'', ''item_name'': ''SPLIT AC IDCACS18K5'', ''vendor_name'': ''Vendor Test Co'', ''customer_name'': ''Cust 1'', ''customer_contact'': ''9876543210''}', '2026-08-04 14:30:15');

-- Table: installation_requests
-- Export mode: sample data (5 of 31 row(s))
DELETE FROM `installation_requests`;
INSERT INTO `installation_requests` (`id`, `customer_name`, `contact_number`, `address`, `order_item_id`, `product_name`, `serial_no`, `serial_no_2`, `request_date`, `assigned_engineer`, `status`, `installation_date`, `work_report`, `work_report_file_path`, `settlement_approved_by`, `created_at`, `updated_at`, `payment_amount_requested`, `payment_type_requested`, `payment_qr_code_path`, `payment_requested_at`, `payment_amount_paid`, `payment_type_paid`, `payment_recorded_at`, `payment_recorded_by`, `payment_proof_file_path`, `payment_qr_code_blob`, `payment_qr_code_filename`, `payment_qr_code_content_type`, `payment_qr_code_size_bytes`, `payment_transaction_id`) VALUES (1, 'Amit Patel', '9876543210', 'Ghaziabad, UP', NULL, 'Split AC 2 Ton', NULL, NULL, '2026-07-29 08:53:39', 2, 'Pending', NULL, NULL, NULL, NULL, '2026-07-29 08:53:39', '2026-07-29 08:53:39', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `installation_requests` (`id`, `customer_name`, `contact_number`, `address`, `order_item_id`, `product_name`, `serial_no`, `serial_no_2`, `request_date`, `assigned_engineer`, `status`, `installation_date`, `work_report`, `work_report_file_path`, `settlement_approved_by`, `created_at`, `updated_at`, `payment_amount_requested`, `payment_type_requested`, `payment_qr_code_path`, `payment_requested_at`, `payment_amount_paid`, `payment_type_paid`, `payment_recorded_at`, `payment_recorded_by`, `payment_proof_file_path`, `payment_qr_code_blob`, `payment_qr_code_filename`, `payment_qr_code_content_type`, `payment_qr_code_size_bytes`, `payment_transaction_id`) VALUES (2, 'Neha Singh', '9876543211', 'Sector 5, Noida', NULL, 'Window AC 1.5 Ton', NULL, NULL, '2026-07-27 08:53:39', 3, 'Assigned', NULL, NULL, NULL, NULL, '2026-07-29 08:53:39', '2026-07-29 08:53:39', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `installation_requests` (`id`, `customer_name`, `contact_number`, `address`, `order_item_id`, `product_name`, `serial_no`, `serial_no_2`, `request_date`, `assigned_engineer`, `status`, `installation_date`, `work_report`, `work_report_file_path`, `settlement_approved_by`, `created_at`, `updated_at`, `payment_amount_requested`, `payment_type_requested`, `payment_qr_code_path`, `payment_requested_at`, `payment_amount_paid`, `payment_type_paid`, `payment_recorded_at`, `payment_recorded_by`, `payment_proof_file_path`, `payment_qr_code_blob`, `payment_qr_code_filename`, `payment_qr_code_content_type`, `payment_qr_code_size_bytes`, `payment_transaction_id`) VALUES (3, 'Rajesh Kumar', '9876543212', 'Greater Noida', NULL, 'Geyser 25L', NULL, NULL, '2026-07-25 08:53:39', 4, 'In Progress', NULL, NULL, NULL, NULL, '2026-07-29 08:53:39', '2026-07-29 08:53:39', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `installation_requests` (`id`, `customer_name`, `contact_number`, `address`, `order_item_id`, `product_name`, `serial_no`, `serial_no_2`, `request_date`, `assigned_engineer`, `status`, `installation_date`, `work_report`, `work_report_file_path`, `settlement_approved_by`, `created_at`, `updated_at`, `payment_amount_requested`, `payment_type_requested`, `payment_qr_code_path`, `payment_requested_at`, `payment_amount_paid`, `payment_type_paid`, `payment_recorded_at`, `payment_recorded_by`, `payment_proof_file_path`, `payment_qr_code_blob`, `payment_qr_code_filename`, `payment_qr_code_content_type`, `payment_qr_code_size_bytes`, `payment_transaction_id`) VALUES (4, 'Meera Rao', '9876543213', 'Faridabad', NULL, 'Fridge 250L', NULL, NULL, '2026-07-23 08:53:39', 2, 'Assigned', NULL, NULL, NULL, NULL, '2026-07-29 08:53:39', '2026-07-29 08:53:39', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `installation_requests` (`id`, `customer_name`, `contact_number`, `address`, `order_item_id`, `product_name`, `serial_no`, `serial_no_2`, `request_date`, `assigned_engineer`, `status`, `installation_date`, `work_report`, `work_report_file_path`, `settlement_approved_by`, `created_at`, `updated_at`, `payment_amount_requested`, `payment_type_requested`, `payment_qr_code_path`, `payment_requested_at`, `payment_amount_paid`, `payment_type_paid`, `payment_recorded_at`, `payment_recorded_by`, `payment_proof_file_path`, `payment_qr_code_blob`, `payment_qr_code_filename`, `payment_qr_code_content_type`, `payment_qr_code_size_bytes`, `payment_transaction_id`) VALUES (5, 'Sanjay Bhatia', '9876543214', 'Jaipur', NULL, 'Air Cooler 40L', NULL, NULL, '2026-07-21 08:53:39', 3, 'Pending', NULL, NULL, NULL, NULL, '2026-07-29 08:53:39', '2026-07-29 08:53:39', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- Table: service_requests
-- Export mode: sample data (5 of 11 row(s))
DELETE FROM `service_requests`;
INSERT INTO `service_requests` (`id`, `request_no`, `request_date`, `query_type`, `customer_name`, `customer_mobile`, `customer_email`, `customer_address`, `model_details`, `problem_description`, `additional_remarks`, `status`, `status_date`, `source`, `created_by`, `order_id`, `order_item_id`, `serial_no`, `service_type`, `warranty_status`, `assigned_engineer_id`, `assigned_vendor_id`, `requires_documents`, `ask_for_documents`, `document_request_sent_at`, `document_access_token`, `customer_identified_at`, `approved_at`, `completed_at`, `closed_at`, `created_at`, `updated_at`, `deleted_at`, `complaint_id`) VALUES (1, 'SRV_1787143076289_1', '2026-07-28', 'Service', 'Demo Service Customer', '9990000001', 'demo-service@example.com', 'Sector 21, Noida, UP', 'SPLIT AC IDCACS18K5', 'AC compressor making rattling noise; intermittent cooling.', NULL, 'Service Team Review', '2026-08-19 12:37:56', 'callcenter', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, 'ken5jmUhKDqP-cQpHzHlfr4gTxr3Ki-C', NULL, NULL, NULL, NULL, '2026-08-19 12:37:56', '2026-08-19 12:37:56', NULL, 1);
INSERT INTO `service_requests` (`id`, `request_no`, `request_date`, `query_type`, `customer_name`, `customer_mobile`, `customer_email`, `customer_address`, `model_details`, `problem_description`, `additional_remarks`, `status`, `status_date`, `source`, `created_by`, `order_id`, `order_item_id`, `serial_no`, `service_type`, `warranty_status`, `assigned_engineer_id`, `assigned_vendor_id`, `requires_documents`, `ask_for_documents`, `document_request_sent_at`, `document_access_token`, `customer_identified_at`, `approved_at`, `completed_at`, `closed_at`, `created_at`, `updated_at`, `deleted_at`, `complaint_id`) VALUES (2, 'SRV_1787143076301_4', '2026-07-28', 'Service', 'Nitin Bansal', '9990000004', 'nitin.bansal@example.com', 'Sector 62, Noida, UP', 'SPLIT AC IDCACS24K5', 'Customer reports unusual noise after startup.', NULL, 'Service Team Review', '2026-08-19 12:37:56', 'callcenter', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, 'bj2jXlvXIeegvLv0rl3cjtJWE7aZlO7_', NULL, NULL, NULL, NULL, '2026-08-19 12:37:56', '2026-08-19 12:37:56', NULL, 4);
INSERT INTO `service_requests` (`id`, `request_no`, `request_date`, `query_type`, `customer_name`, `customer_mobile`, `customer_email`, `customer_address`, `model_details`, `problem_description`, `additional_remarks`, `status`, `status_date`, `source`, `created_by`, `order_id`, `order_item_id`, `serial_no`, `service_type`, `warranty_status`, `assigned_engineer_id`, `assigned_vendor_id`, `requires_documents`, `ask_for_documents`, `document_request_sent_at`, `document_access_token`, `customer_identified_at`, `approved_at`, `completed_at`, `closed_at`, `created_at`, `updated_at`, `deleted_at`, `complaint_id`) VALUES (3, 'SRV_1787143076304_5', '2026-07-28', 'Service', 'Anjali Rao', '9990000005', 'anjali.rao@example.com', 'Whitefield, Bengaluru, KA', 'FRIDGE IDCFRD360L', 'Customer wants a service visit for cooling issue.', NULL, 'Service Team Review', '2026-08-19 12:37:56', 'callcenter', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, 'rfGT1PDvvJok6x8vZQybRrOEcmK7iHUL', NULL, NULL, NULL, NULL, '2026-08-19 12:37:56', '2026-08-19 12:37:56', NULL, 5);
INSERT INTO `service_requests` (`id`, `request_no`, `request_date`, `query_type`, `customer_name`, `customer_mobile`, `customer_email`, `customer_address`, `model_details`, `problem_description`, `additional_remarks`, `status`, `status_date`, `source`, `created_by`, `order_id`, `order_item_id`, `serial_no`, `service_type`, `warranty_status`, `assigned_engineer_id`, `assigned_vendor_id`, `requires_documents`, `ask_for_documents`, `document_request_sent_at`, `document_access_token`, `customer_identified_at`, `approved_at`, `completed_at`, `closed_at`, `created_at`, `updated_at`, `deleted_at`, `complaint_id`) VALUES (4, 'SRV_1787143076310_6', '2026-07-31', 'Service', 'API-QA-0c623bcd Complaint', '9990004444', 'qa.complaint@example.com', 'QA complaint address', 'AIR COOLER IDCCLR40L', 'Cooling issue for backend regression', 'Assigned during API regression', 'Service Team Review', '2026-08-19 12:37:56', 'callcenter', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, '9p1BL9GNiYKRMQlEcc8M9RZpwcsCXnly', NULL, NULL, NULL, NULL, '2026-08-19 12:37:56', '2026-08-19 12:37:56', NULL, 6);
INSERT INTO `service_requests` (`id`, `request_no`, `request_date`, `query_type`, `customer_name`, `customer_mobile`, `customer_email`, `customer_address`, `model_details`, `problem_description`, `additional_remarks`, `status`, `status_date`, `source`, `created_by`, `order_id`, `order_item_id`, `serial_no`, `service_type`, `warranty_status`, `assigned_engineer_id`, `assigned_vendor_id`, `requires_documents`, `ask_for_documents`, `document_request_sent_at`, `document_access_token`, `customer_identified_at`, `approved_at`, `completed_at`, `closed_at`, `created_at`, `updated_at`, `deleted_at`, `complaint_id`) VALUES (5, 'SRV_1787143076313_7', '2026-07-31', 'Service', 'API-QA-f69170de Complaint', '9990004444', 'qa.complaint@example.com', 'QA complaint address', 'AIR COOLER IDCCLR40L', 'Cooling issue for backend regression', 'Assigned during API regression', 'Service Team Review', '2026-08-19 12:37:56', 'callcenter', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, '9qv0ysZT4jpo9BsqEtpCnWvGhFXnnm45', NULL, NULL, NULL, NULL, '2026-08-19 12:37:56', '2026-08-19 12:37:56', NULL, 7);

-- Table: service_assignments
-- Export mode: sample data (3 of 3 row(s))
DELETE FROM `service_assignments`;
INSERT INTO `service_assignments` (`id`, `service_request_id`, `assignee_type`, `assignee_user_id`, `assignee_vendor_id`, `assigned_by`, `assigned_at`, `remarks`, `is_active`) VALUES (1, 9, 'engineer', 2, NULL, 1, '2026-08-20 15:55:06', '', 1);
INSERT INTO `service_assignments` (`id`, `service_request_id`, `assignee_type`, `assignee_user_id`, `assignee_vendor_id`, `assigned_by`, `assigned_at`, `remarks`, `is_active`) VALUES (2, 10, 'engineer', 2, NULL, 1, '2026-08-20 17:46:28', 'check  ', 1);
INSERT INTO `service_assignments` (`id`, `service_request_id`, `assignee_type`, `assignee_user_id`, `assignee_vendor_id`, `assigned_by`, `assigned_at`, `remarks`, `is_active`) VALUES (3, 11, 'engineer', 3, NULL, 1, '2026-08-21 05:52:36', '', 1);

-- Table: service_completions
-- Export mode: sample data (3 of 3 row(s))
DELETE FROM `service_completions`;
INSERT INTO `service_completions` (`id`, `service_request_id`, `performed_by_type`, `performed_by_user_id`, `performed_by_vendor_id`, `work_performed`, `parts_replaced_json`, `service_notes`, `service_date`, `before_photos_json`, `after_photos_json`, `customer_acknowledgement_path`, `final_amount`, `completion_remarks`, `completed_at`, `old_part_serial_no`, `new_part_serial_no`) VALUES (4, 9, 'engineer', 2, NULL, 'gas filled', NULL, '', '2026-08-19', NULL, NULL, '/uploads/services/2026/08/907d74fac42c4ace8d52992be7868514.jpg', 3200.00, '', '2026-08-20 17:17:04', NULL, NULL);
INSERT INTO `service_completions` (`id`, `service_request_id`, `performed_by_type`, `performed_by_user_id`, `performed_by_vendor_id`, `work_performed`, `parts_replaced_json`, `service_notes`, `service_date`, `before_photos_json`, `after_photos_json`, `customer_acknowledgement_path`, `final_amount`, `completion_remarks`, `completed_at`, `old_part_serial_no`, `new_part_serial_no`) VALUES (5, 10, 'engineer', 2, NULL, 'gasket replacment and refill gas', '["gaskey"]', '', '2026-08-20', NULL, NULL, '/uploads/services/2026/08/76f70aabbf2a43d28d9b27376c5da5e1.jpg', 3200.00, '', '2026-08-20 17:48:57', NULL, NULL);
INSERT INTO `service_completions` (`id`, `service_request_id`, `performed_by_type`, `performed_by_user_id`, `performed_by_vendor_id`, `work_performed`, `parts_replaced_json`, `service_notes`, `service_date`, `before_photos_json`, `after_photos_json`, `customer_acknowledgement_path`, `final_amount`, `completion_remarks`, `completed_at`, `old_part_serial_no`, `new_part_serial_no`) VALUES (6, 11, 'engineer', 3, NULL, 'replace pcb ,normal servicing', '["pcb"]', 'replace pcb ,normal servicing', '2026-08-21', NULL, NULL, '/uploads/services/2026/08/e807ee81439440d696b3f72f1b33e587.jpg', 7800.00, '', '2026-08-21 05:59:03', NULL, NULL);

-- Table: service_documents
-- Export mode: sample data (3 of 3 row(s))
DELETE FROM `service_documents`;
INSERT INTO `service_documents` (`id`, `service_request_id`, `document_type`, `file_path`, `uploaded_by_type`, `uploaded_by_user_id`, `uploaded_by_customer_name`, `status`, `reviewed_by`, `reviewed_at`, `review_remarks`, `uploaded_at`) VALUES (3, 7, 'Original Purchase Bill/Invoice', '/uploads/services/2026/08/6ab899742b42484abcdb68f99ce04450.pdf', 'customer', NULL, 'Rajeev dubey', 'Uploaded', NULL, NULL, NULL, '2026-08-19 16:16:06');
INSERT INTO `service_documents` (`id`, `service_request_id`, `document_type`, `file_path`, `uploaded_by_type`, `uploaded_by_user_id`, `uploaded_by_customer_name`, `status`, `reviewed_by`, `reviewed_at`, `review_remarks`, `uploaded_at`) VALUES (4, 9, 'Original Purchase Bill/Invoice', '/uploads/services/2026/08/d56eb0644f734690b8a52f1106e5752c.pdf', 'customer', NULL, 'testdj', 'Reviewed', 1, '2026-08-19 17:30:07', 'Reviewed', '2026-08-19 17:29:52');
INSERT INTO `service_documents` (`id`, `service_request_id`, `document_type`, `file_path`, `uploaded_by_type`, `uploaded_by_user_id`, `uploaded_by_customer_name`, `status`, `reviewed_by`, `reviewed_at`, `review_remarks`, `uploaded_at`) VALUES (5, 10, 'Original Purchase Bill/Invoice', '/uploads/services/2026/08/2d245403db0f4a74b26e8417cf0312bf.jpg', 'customer', NULL, 'Rajeev ranjan dubey', 'Uploaded', NULL, NULL, NULL, '2026-08-20 17:45:32');

-- Table: service_notifications
-- Export mode: sample data (5 of 5 row(s))
DELETE FROM `service_notifications`;
INSERT INTO `service_notifications` (`id`, `service_request_id`, `recipient_user_id`, `recipient_vendor_id`, `title`, `message`, `notification_type`, `is_read`, `read_at`, `created_at`, `updated_at`) VALUES (1, 7, 1, NULL, 'Customer documents received', 'Customer uploaded Original Purchase Bill/Invoice for SRV_1787143076320_9.', 'customer_document_uploaded', 1, '2026-08-19 15:58:00', '2026-08-19 15:52:30', '2026-08-19 21:27:59');
INSERT INTO `service_notifications` (`id`, `service_request_id`, `recipient_user_id`, `recipient_vendor_id`, `title`, `message`, `notification_type`, `is_read`, `read_at`, `created_at`, `updated_at`) VALUES (2, 7, 1, NULL, 'Customer documents received', 'Customer uploaded Original Purchase Bill/Invoice for SRV_1787143076320_9.', 'customer_document_uploaded', 1, '2026-08-19 15:58:00', '2026-08-19 15:57:36', '2026-08-19 21:27:59');
INSERT INTO `service_notifications` (`id`, `service_request_id`, `recipient_user_id`, `recipient_vendor_id`, `title`, `message`, `notification_type`, `is_read`, `read_at`, `created_at`, `updated_at`) VALUES (3, 7, 1, NULL, 'Customer documents received', 'Customer uploaded Original Purchase Bill/Invoice for SRV_1787143076320_9.', 'customer_document_uploaded', 1, '2026-08-19 16:16:14', '2026-08-19 16:16:06', '2026-08-19 21:46:13');
INSERT INTO `service_notifications` (`id`, `service_request_id`, `recipient_user_id`, `recipient_vendor_id`, `title`, `message`, `notification_type`, `is_read`, `read_at`, `created_at`, `updated_at`) VALUES (4, 9, 1, NULL, 'Customer documents received', 'Customer uploaded Original Purchase Bill/Invoice for SRV_1787160543298.', 'customer_document_uploaded', 1, '2026-08-19 17:29:59', '2026-08-19 17:29:52', '2026-08-19 22:59:59');
INSERT INTO `service_notifications` (`id`, `service_request_id`, `recipient_user_id`, `recipient_vendor_id`, `title`, `message`, `notification_type`, `is_read`, `read_at`, `created_at`, `updated_at`) VALUES (5, 10, 1, NULL, 'Customer documents received', 'Customer uploaded Original Purchase Bill/Invoice for SRV_1787247899789.', 'customer_document_uploaded', 1, '2026-08-20 17:45:38', '2026-08-20 17:45:32', '2026-08-20 23:15:37');

-- Table: service_observations
-- Export mode: sample data (4 of 4 row(s))
DELETE FROM `service_observations`;
INSERT INTO `service_observations` (`id`, `service_request_id`, `submitted_by_user_id`, `serial_no`, `warranty_status`, `service_type`, `problem_found`, `observation`, `recommended_action`, `parts_required_json`, `estimated_service_charge`, `estimated_parts_charge`, `remarks`, `submitted_at`) VALUES (1, 9, 2, '123', 'IN WARRANTY', 'Free Service', 'gas issue', '', 'refill gas', NULL, 2000.00, NULL, '', '2026-08-20 16:41:06');
INSERT INTO `service_observations` (`id`, `service_request_id`, `submitted_by_user_id`, `serial_no`, `warranty_status`, `service_type`, `problem_found`, `observation`, `recommended_action`, `parts_required_json`, `estimated_service_charge`, `estimated_parts_charge`, `remarks`, `submitted_at`) VALUES (3, 9, 2, '123', 'IN WARRANTY', 'Free Service', 'gas issue', '', 'refill gas', NULL, 2000.00, NULL, '', '2026-08-20 16:49:00');
INSERT INTO `service_observations` (`id`, `service_request_id`, `submitted_by_user_id`, `serial_no`, `warranty_status`, `service_type`, `problem_found`, `observation`, `recommended_action`, `parts_required_json`, `estimated_service_charge`, `estimated_parts_charge`, `remarks`, `submitted_at`) VALUES (4, 10, 2, '103012345678', 'IN WARRANTY', 'Free Service', 'gas leak', '', '', '["gasket replacment"]', 2000.00, 1200.00, '', '2026-08-20 17:47:27');
INSERT INTO `service_observations` (`id`, `service_request_id`, `submitted_by_user_id`, `serial_no`, `warranty_status`, `service_type`, `problem_found`, `observation`, `recommended_action`, `parts_required_json`, `estimated_service_charge`, `estimated_parts_charge`, `remarks`, `submitted_at`) VALUES (5, 11, 3, 'IDC-0077', 'IN WARRANTY', 'Free Service', 'pcb burned', 'pcb need to replaced', '', '["PCB"]', 1500.00, 7000.00, '', '2026-08-21 05:55:35');

-- Table: service_payment_requests
-- Export mode: sample data (3 of 3 row(s))
DELETE FROM `service_payment_requests`;
INSERT INTO `service_payment_requests` (`id`, `service_request_id`, `requested_by_type`, `requested_by_user_id`, `requested_by_vendor_id`, `service_type`, `customer_charge_amount`, `settlement_service_amount`, `settlement_parts_amount`, `total_requested_amount`, `payment_type`, `remarks`, `status`, `processed_at`, `created_at`, `updated_at`, `processed_by_user_id`, `payment_transaction_id`, `payment_qr_code_path`, `approved_amount`) VALUES (3, 9, 'engineer', 2, NULL, 'Free Service', 0.00, 3200.00, NULL, NULL, 'UPI', 'approved after QR scan', 'Processed', '2026-08-20 17:43:18', '2026-08-20 17:17:36', '2026-08-20 17:43:18', 1, 3, '/uploads/services/2026/08/1bc83d098beb4cb59e5ac7566d797aa5.png', 2500.00);
INSERT INTO `service_payment_requests` (`id`, `service_request_id`, `requested_by_type`, `requested_by_user_id`, `requested_by_vendor_id`, `service_type`, `customer_charge_amount`, `settlement_service_amount`, `settlement_parts_amount`, `total_requested_amount`, `payment_type`, `remarks`, `status`, `processed_at`, `created_at`, `updated_at`, `processed_by_user_id`, `payment_transaction_id`, `payment_qr_code_path`, `approved_amount`) VALUES (4, 10, 'engineer', 2, NULL, 'Free Service', 0.00, 3200.00, NULL, 3200.00, 'UPI', '2500 is ok ', 'Processed', '2026-08-20 17:50:10', '2026-08-20 17:49:32', '2026-08-20 17:50:10', 1, 4, '/uploads/services/2026/08/0db7d9c818d74960af38cb52aa7abab1.png', 2500.00);
INSERT INTO `service_payment_requests` (`id`, `service_request_id`, `requested_by_type`, `requested_by_user_id`, `requested_by_vendor_id`, `service_type`, `customer_charge_amount`, `settlement_service_amount`, `settlement_parts_amount`, `total_requested_amount`, `payment_type`, `remarks`, `status`, `processed_at`, `created_at`, `updated_at`, `processed_by_user_id`, `payment_transaction_id`, `payment_qr_code_path`, `approved_amount`) VALUES (5, 11, 'engineer', 3, NULL, 'Free Service', NULL, NULL, NULL, 7800.00, 'UPI', '', 'Processed', '2026-08-21 06:00:05', '2026-08-21 05:59:31', '2026-08-21 06:00:05', 1, 6, '/uploads/services/2026/08/4c7a97ced3a441f5a4bf4a007b2dc31d.png', 7800.00);

-- Table: service_status_logs
-- Export mode: sample data (5 of 73 row(s))
DELETE FROM `service_status_logs`;
INSERT INTO `service_status_logs` (`id`, `service_request_id`, `action`, `old_status`, `new_status`, `performed_by`, `performed_role`, `remarks`, `metadata_json`, `created_at`, `serial_history_source_id`) VALUES (1, 7, 'Documents Requested', 'Service Team Review', 'Service Team Review', 1, 'admin', NULL, '{"upload_url": "http://localhost:5173/services/public-upload/I09hHMuIuW_AZM4wOwQ_OenPZBVCE3oP", "required_documents": ["Original Purchase Bill/Invoice", "Purchase Order"], "requested_by_host": "http://localhost:8010"}', '2026-08-19 12:43:27', NULL);
INSERT INTO `service_status_logs` (`id`, `service_request_id`, `action`, `old_status`, `new_status`, `performed_by`, `performed_role`, `remarks`, `metadata_json`, `created_at`, `serial_history_source_id`) VALUES (2, 7, 'Documents Requested', 'Service Team Review', 'Service Team Review', 1, 'admin', NULL, '{"upload_url": "http://localhost:5173/services/public-upload/nN0WIyaNswo6jsyCRau0mE1CrKW9zXQm", "required_documents": ["Original Purchase Bill/Invoice", "Purchase Order"], "requested_by_host": "http://localhost:8010"}', '2026-08-19 15:49:14', NULL);
INSERT INTO `service_status_logs` (`id`, `service_request_id`, `action`, `old_status`, `new_status`, `performed_by`, `performed_role`, `remarks`, `metadata_json`, `created_at`, `serial_history_source_id`) VALUES (5, 7, 'Documents Requested', 'Service Team Review', 'Service Team Review', 1, 'admin', NULL, '{"upload_url": "http://localhost:5173/services/public-upload/0gClHgiYo0XP2FG5jLtDOGtQ0rl8pKAC", "required_documents": ["Original Purchase Bill/Invoice", "Purchase Order"], "requested_by_host": "http://localhost:8010"}', '2026-08-19 16:15:47', NULL);
INSERT INTO `service_status_logs` (`id`, `service_request_id`, `action`, `old_status`, `new_status`, `performed_by`, `performed_role`, `remarks`, `metadata_json`, `created_at`, `serial_history_source_id`) VALUES (6, 7, 'Customer Document Uploaded', 'Service Team Review', 'Service Team Review', NULL, 'customer', 'Original Purchase Bill/Invoice', '{"document_type": "Original Purchase Bill/Invoice", "file_path": "/uploads/services/2026/08/6ab899742b42484abcdb68f99ce04450.pdf"}', '2026-08-19 16:16:06', NULL);
INSERT INTO `service_status_logs` (`id`, `service_request_id`, `action`, `old_status`, `new_status`, `performed_by`, `performed_role`, `remarks`, `metadata_json`, `created_at`, `serial_history_source_id`) VALUES (7, 9, 'Documents Requested', 'Service Team Review', 'Service Team Review', 1, 'admin', NULL, '{"upload_url": "http://localhost:5173/services/public-upload/_-Dg11IkbZ2NkZRiDH0xSoEO7cj6paPl", "required_documents": ["Original Purchase Bill/Invoice", "Purchase Order"], "requested_by_host": "http://localhost:8010"}', '2026-08-19 17:29:34', NULL);

-- Table: service_approvals
-- Export mode: sample data (3 of 3 row(s))
DELETE FROM `service_approvals`;
INSERT INTO `service_approvals` (`id`, `service_request_id`, `observation_id`, `decision`, `remarks`, `approved_by`, `approved_at`) VALUES (8, 9, 3, 'Approve', '', 1, '2026-08-20 17:15:30');
INSERT INTO `service_approvals` (`id`, `service_request_id`, `observation_id`, `decision`, `remarks`, `approved_by`, `approved_at`) VALUES (9, 10, 4, 'Approve', '', 1, '2026-08-20 17:47:56');
INSERT INTO `service_approvals` (`id`, `service_request_id`, `observation_id`, `decision`, `remarks`, `approved_by`, `approved_at`) VALUES (10, 11, 5, 'Approve', '7800 will paid no charge from customer', 1, '2026-08-21 05:57:52');

COMMIT;
SET FOREIGN_KEY_CHECKS=1;
