-- PostgreSQL-compatible DDL for the CRMPOC application
-- Run with: psql -U <user> -d <database> -f api/sql/create_tables_postgres.sql

BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(100) NOT NULL DEFAULT 'callcenter',
    phone VARCHAR(20),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS ix_users_email ON users (email);

CREATE TABLE IF NOT EXISTS roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS permissions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    module VARCHAR(100) NOT NULL,
    sub_module VARCHAR(100),
    can_view BOOLEAN NOT NULL DEFAULT FALSE,
    can_create BOOLEAN NOT NULL DEFAULT FALSE,
    can_edit BOOLEAN NOT NULL DEFAULT FALSE,
    can_delete BOOLEAN NOT NULL DEFAULT FALSE,
    can_export BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS item_masters (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code VARCHAR(100) NOT NULL UNIQUE,
    item_name VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    description TEXT,
    brand VARCHAR(100),
    unit VARCHAR(50),
    hsn_code VARCHAR(20),
    mrp NUMERIC(10,2),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS ix_item_masters_item_code ON item_masters (item_code);

CREATE TABLE IF NOT EXISTS vendors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_code VARCHAR(50) NOT NULL UNIQUE,
    name_of_firm VARCHAR(255) NOT NULL,
    contact_name VARCHAR(255),
    contact_mobile VARCHAR(20),
    email VARCHAR(255),
    gst_no VARCHAR(20),
    address TEXT,
    state VARCHAR(100),
    district VARCHAR(100),
    pincode VARCHAR(10),
    latitude NUMERIC(10,8),
    longitude NUMERIC(11,8),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS ix_vendors_vendor_code ON vendors (vendor_code);

CREATE TABLE IF NOT EXISTS couriers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    courier_name VARCHAR(255) NOT NULL,
    contact_name VARCHAR(255),
    contact_mobile VARCHAR(20),
    email VARCHAR(255),
    address TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(255) UNIQUE,
    order_date DATE NOT NULL,
    oem_bill_no VARCHAR(100),
    vendor_id INTEGER REFERENCES vendors(id),
    customer_name VARCHAR(255),
    customer_contact VARCHAR(20),
    customer_email VARCHAR(255),
    customer_city VARCHAR(100),
    customer_state VARCHAR(100),
    customer_address TEXT,
    courier_id INTEGER REFERENCES couriers(id),
    lrn_no VARCHAR(100),
    vendor_bill_no VARCHAR(100),
    vendor_bill_date DATE,
    status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    expected_delivery_date DATE,
    actual_delivery_date DATE,
    order_file_path VARCHAR(500),
    created_by INTEGER REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS ix_orders_order_no ON orders (order_no);
CREATE INDEX IF NOT EXISTS ix_orders_status ON orders (status);
CREATE INDEX IF NOT EXISTS ix_orders_vendor_id ON orders (vendor_id);

CREATE TABLE IF NOT EXISTS order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    item_id INTEGER REFERENCES item_masters(id),
    serial_no VARCHAR(100),
    serial_no_2 VARCHAR(100),
    item_qty INTEGER NOT NULL DEFAULT 1,
    pcb_warranty_years INTEGER,
    component_warranty_years INTEGER,
    machine_warranty_years INTEGER,
    free_service_count INTEGER NOT NULL DEFAULT 0,
    service_consume_count INTEGER NOT NULL DEFAULT 0,
    installation_status VARCHAR(50) NOT NULL DEFAULT 'Not Requested',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_order_items_serial_no ON order_items (serial_no);
CREATE INDEX IF NOT EXISTS ix_order_items_order_id ON order_items (order_id);

CREATE TABLE IF NOT EXISTS complaints (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comp_no VARCHAR(100) NOT NULL UNIQUE,
    comp_date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer_name VARCHAR(255) NOT NULL,
    customer_mobile VARCHAR(20) NOT NULL,
    customer_email VARCHAR(255),
    customer_address TEXT,
    model_details VARCHAR(255),
    problem_description TEXT,
    query_type VARCHAR(50),
    status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    status_date TIMESTAMPTZ,
    assigned_engineer INTEGER REFERENCES users(id),
    remark TEXT,
    service_proof_path VARCHAR(500),
    access_code VARCHAR(100),
    send_sms BOOLEAN NOT NULL DEFAULT TRUE,
    created_by INTEGER REFERENCES users(id),
    source VARCHAR(50) NOT NULL DEFAULT 'callcenter',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS ix_complaints_comp_no ON complaints (comp_no);
CREATE INDEX IF NOT EXISTS ix_complaints_customer_mobile ON complaints (customer_mobile);
CREATE INDEX IF NOT EXISTS ix_complaints_status ON complaints (status);

CREATE TABLE IF NOT EXISTS complaint_status_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id INTEGER NOT NULL REFERENCES complaints(id),
    old_status VARCHAR(50),
    new_status VARCHAR(50),
    changed_by INTEGER REFERENCES users(id),
    remark TEXT,
    document_path VARCHAR(500),
    action_taken VARCHAR(100),
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS installation_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL,
    contact_number VARCHAR(20) NOT NULL,
    address TEXT,
    order_item_id INTEGER REFERENCES order_items(id),
    product_name VARCHAR(255),
    serial_no VARCHAR(100),
    serial_no_2 VARCHAR(100),
    request_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_engineer INTEGER REFERENCES users(id),
    status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    installation_date TIMESTAMPTZ,
    work_report TEXT,
    work_report_file_path VARCHAR(500),
    settlement_approved_by INTEGER REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_installation_requests_request_date ON installation_requests (request_date);
CREATE INDEX IF NOT EXISTS ix_installation_requests_status ON installation_requests (status);

CREATE TABLE IF NOT EXISTS calls (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref_no VARCHAR(100) NOT NULL UNIQUE,
    customer_name VARCHAR(255),
    customer_email VARCHAR(255),
    phone VARCHAR(20),
    call_type VARCHAR(20),
    status VARCHAR(30),
    priority VARCHAR(20) NOT NULL DEFAULT 'medium',
    assigned_to INTEGER REFERENCES users(id),
    transferred_to INTEGER REFERENCES users(id),
    is_transferred BOOLEAN NOT NULL DEFAULT FALSE,
    duration_secs INTEGER,
    call_datetime TIMESTAMPTZ NOT NULL,
    followup_date TIMESTAMPTZ,
    notes TEXT,
    follow_up_notes TEXT,
    follow_up_status VARCHAR(30),
    complaint_id INTEGER REFERENCES complaints(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_calls_status ON calls (status);
CREATE INDEX IF NOT EXISTS ix_calls_followup_date ON calls (followup_date);

CREATE TABLE IF NOT EXISTS claims (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id VARCHAR(100) NOT NULL UNIQUE,
    order_no VARCHAR(255),
    serial_number VARCHAR(100),
    order_item_id INTEGER REFERENCES order_items(id),
    customer_name VARCHAR(255),
    customer_contact VARCHAR(20),
    customer_email VARCHAR(255),
    status VARCHAR(50) NOT NULL DEFAULT 'Processing',
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_by INTEGER REFERENCES users(id),
    notes TEXT,
    bank_name VARCHAR(100),
    account_holder_name VARCHAR(255),
    account_number VARCHAR(100),
    ifsc_code VARCHAR(20),
    admin_remark TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_claims_claim_id ON claims (claim_id);

CREATE TABLE IF NOT EXISTS claim_photos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id INTEGER NOT NULL REFERENCES claims(id) ON DELETE CASCADE,
    file_path VARCHAR(500) NOT NULL,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS market_categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    parent_id INTEGER REFERENCES market_categories(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS market_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    company VARCHAR(100),
    category_id INTEGER REFERENCES market_categories(id),
    base_price NUMERIC(10,2),
    mrp NUMERIC(10,2),
    image_path VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'Active',
    stock_count INTEGER NOT NULL DEFAULT 0,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_market_items_sku ON market_items (sku);

CREATE TABLE IF NOT EXISTS market_users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20),
    address TEXT,
    city VARCHAR(100),
    state VARCHAR(100),
    role VARCHAR(50) NOT NULL DEFAULT 'Retailer',
    status VARCHAR(20) NOT NULL DEFAULT 'Pending',
    fee_status VARCHAR(20) NOT NULL DEFAULT 'Pending',
    onboarding_fee NUMERIC(10,2),
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS market_orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(50) NOT NULL UNIQUE,
    retailer_id INTEGER REFERENCES market_users(id),
    distributor_id INTEGER REFERENCES market_users(id),
    total_amount NUMERIC(12,2),
    status VARCHAR(20) NOT NULL DEFAULT 'Pending',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS market_order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES market_orders(id) ON DELETE CASCADE,
    item_id INTEGER REFERENCES market_items(id),
    qty INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC(10,2),
    subtotal NUMERIC(12,2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'Draft',
    owner_id INTEGER REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_projects_status ON projects (status);

CREATE TABLE IF NOT EXISTS workflow_tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    task_name VARCHAR(255) NOT NULL,
    task_type VARCHAR(50) NOT NULL,
    sequence INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL DEFAULT 'Pending',
    advisor_id VARCHAR(100),
    input_data TEXT,
    output_data TEXT,
    error_message TEXT,
    started_at VARCHAR(50),
    completed_at VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_workflow_tasks_project_id ON workflow_tasks (project_id);

COMMIT;
